using System.Collections.Generic;

// ReSharper disable InconsistentNaming

namespace AnkiEditor.Models
{

    // generated by http://json2csharp.com/

    // TODO: we do not support child decks
    public class Lapse
    {
        public List<int> delays { get; set; }
        public int leechAction { get; set; }
        public int leechFails { get; set; }
        public int minInt { get; set; }
        public double mult { get; set; }
    }

    public class New
    {
        public bool bury { get; set; }
        public List<int> delays { get; set; }
        public int initialFactor { get; set; }
        public List<int> ints { get; set; }
        public int order { get; set; }
        public int perDay { get; set; }
        public bool separate { get; set; }
    }

    public class Rev
    {
        public bool bury { get; set; }
        public double ease4 { get; set; }
        public double fuzz { get; set; }
        public double ivlFct { get; set; }
        public int maxIvl { get; set; }
        public int minSpace { get; set; }
        public int perDay { get; set; }
    }

    public class DeckConfiguration
    {
        public string __type__ { get; set; }
        public bool autoplay { get; set; }
        public string crowdanki_uuid { get; set; }
        public bool dyn { get; set; }
        public Lapse lapse { get; set; }
        public int maxTaken { get; set; }
        public string name { get; set; }
        public New @new { get; set; }
        public bool replayq { get; set; }
        public Rev rev { get; set; }
        public int timer { get; set; }
    }

    public class Fld
    {
        public string font { get; set; }
        public List<object> media { get; set; }
        public string name { get; set; }
        public int ord { get; set; }
        public bool rtl { get; set; }
        public int size { get; set; }
        public bool sticky { get; set; }
    }

    public class Tmpl
    {
        public string afmt { get; set; }
        public string bafmt { get; set; }
        public string bqfmt { get; set; }
        public object did { get; set; }
        public string name { get; set; }
        public int ord { get; set; }
        public string qfmt { get; set; }
        public int scratchPad { get; set; }
    }

    public class NoteModel
    {
        public string __type__ { get; set; }
        public string crowdanki_uuid { get; set; }
        public string css { get; set; }
        public List<Fld> flds { get; set; }
        public string latexPost { get; set; }
        public string latexPre { get; set; }
        public string name { get; set; }
        public List<List<object>> req { get; set; }
        public int sortf { get; set; }
        public List<string> tags { get; set; }
        public List<Tmpl> tmpls { get; set; }
        public int type { get; set; }
        public List<object> vers { get; set; }
    }

    public class Note
    {
        public string __type__ { get; set; }
        public string data { get; set; }
        public List<string> fields { get; set; }
        public int flags { get; set; }
        public string guid { get; set; }
        public string note_model_uuid { get; set; }
        public List<string> tags { get; set; }
    }

    public class Deck
    {
        public string __type__ { get; set; }
        public List<object> children { get; set; }
        public string crowdanki_uuid { get; set; }
        public string deck_config_uuid { get; set; }
        public List<DeckConfiguration> deck_configurations { get; set; }
        public string desc { get; set; }
        public int dyn { get; set; }
        public int extendNew { get; set; }
        public int extendRev { get; set; }
        public List<string> media_files { get; set; }
        public long mid { get; set; }
        public string name { get; set; }
        public List<NoteModel> note_models { get; set; }
        public List<Note> notes { get; set; }
    }
}
